sudo: true
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      
script:
- export EXPLORER_LOG_PATH="log.txt"
- cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install -DBUILD_TESTS=ON
- cmake --build _build
- cd _build
- ls
- ./explorer CMakeFiles
- ls
- cd ..
- cmake --build _build --target install
- cd _build
- ls
- cd ..
- cmake --build _build --target test
