sudo: true
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      
script:
- export EXPLORER_LOG_PATH="log.txt"
- cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install -DBUILD_TESTS=ON -DCPACK_GENERATOR=TGZ
- cmake --build _build
- cd _build
- ./explorer CMakeCache.txt
- cd ..
- cmake --build _build --target install		
- cmake --build _build --target test
- cmake --build _build --target package
- mv _build/*.tar.gz artifacts
